/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FriendshipSchema extends BaseModel {
  static $columns = ['createdAt', 'friendId', 'id', 'status', 'updatedAt', 'userId'] as const
  $columns = FriendshipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare friendId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LessonCompletionSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'id', 'lessonId', 'updatedAt', 'userId'] as const
  $columns = LessonCompletionSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lessonId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'username'] as const
  $columns = ProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare id: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
