FROM node:26.1.0-bookworm-slim AS base

# ----------------------------
# Stage 1: Install all dependencies
# ----------------------------
FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# ----------------------------
# Stage 2: Build the application
# ----------------------------
FROM deps AS build
WORKDIR /app
COPY . .
RUN node ace build

# ----------------------------
# Stage 3: Production runtime
# ----------------------------
FROM base AS production
WORKDIR /app
ENV NODE_ENV=production

COPY ./startup.sh /
RUN chmod +x /startup.sh

COPY --from=build /app/build ./
RUN npm ci --omit=dev

EXPOSE 3333

CMD ["bash", "/startup.sh"]