/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessObjects: () => import('#controllers/access_objects_controller'),
  Quotas: () => import('#controllers/quotas_controller'),
}
