/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessObjects: () => import('#controllers/access_objects_controller'),
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  GetSignedUrls: () => import('#controllers/get_signed_urls_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  ProfileAvatars: () => import('#controllers/profile_avatars_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
