/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamPaperAnswerSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'examPaperId', 'examsQuestionId', 'id', 'isCorrect', 'updatedAt'] as const
  $columns = ExamPaperAnswerSchema.$columns
  @column()
  declare answer: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare examPaperId: number
  @column()
  declare examsQuestionId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamPaperSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'examId', 'id', 'score', 'startedAt', 'status', 'totalPoints', 'updatedAt', 'userId'] as const
  $columns = ExamPaperSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare examId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: number | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string | null
  @column()
  declare totalPoints: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ExamSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lessonRelatedId', 'questions', 'title', 'updatedAt', 'userId'] as const
  $columns = ExamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lessonRelatedId: string | null
  @column()
  declare questions: any | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ExamsQuestionSchema extends BaseModel {
  static $columns = ['createdAt', 'examId', 'id', 'points', 'position', 'questionId', 'updatedAt'] as const
  $columns = ExamsQuestionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare examId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare points: number | null
  @column()
  declare position: number | null
  @column()
  declare questionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuestionSchema extends BaseModel {
  static $columns = ['badAnswers', 'createdAt', 'goodAnswers', 'id', 'questionType', 'title', 'updatedAt'] as const
  $columns = QuestionSchema.$columns
  @column()
  declare badAnswers: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare goodAnswers: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare questionType: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
