/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Friends: () => import('#controllers/friends_controller'),
  Users: () => import('#controllers/users_controller'),
}
